version: "3.9"
services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: app-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
